# _config.yml
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
gh_sponsor: brownrw8
footer_menu: footer
theme_color: rebeccapurple
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
      title: ""
      hero_image: /images/hero_80s.png

