# _config.yml
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
gh_sponsor: brownrw8
footer_menu: footer
theme_color: rebeccapurple
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
      title: ""
      hero_image: /images/hero_80s.png
  - scope:
      path: "/promo"
      type: "pages"
    values:
      title: "ʻŌlelo Honua"
      subtitle: "`npm i olelo-honua`"
      snippet: |-
        Bloom your i18n workflow!
      layout: promo-page
      hero_link: https://olelohonua.com
      hero_link_text: Learn More
      hero_image: /images/logo.png
      hero_image_alt: The hero image alt text
      hero_image_ratio: is-5by5
